name: Bulldozer Platform ci
on: pull_request
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - id: config-repo
        name: Pre config - 🧰 Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: config-node
        name: Pre config - 🧰 Setting up Node 14.7.5
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.5' # we have to check this

      - id: install-npm-packages
        name: 📦 Git fetch for affected commands and installing npm packages
        run: |
          git fetch --no-tags --prune --depth=2 origin master
          npm i

      - id: get-affected-projects
        name: 🛠️ Getting affected projects
        shell: bash
        # Here we use the `npx nx print-affected` command to get all the affected projects in a single string
        # then using grep, we count (using the -c flag) the occurrences of 'bulldozer-program' string in the above result
        # if we get 0, it means the bulldozer-program does not changed, otherwise it changed and we will install Anchor
        run: |
          echo "::set-output name=bulldozer-program-affected::$(echo $(npx nx print-affected --select=projects --base=origin/master) | grep -c "bulldozer-programs")"

      - id: install-anchor
        name: 🛠️ Setting up Anchor, Rust, Solana and others related dependencies
        if: steps.get-affected-projects.outputs.bulldozer-program-affected != 0
        run: |
          echo "Installing Rust >>"
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup component add rustfmt

          echo "Installing Solana >> "
          sh -c "$(curl -sSfL https://release.solana.com/v1.7.11/install)"
          echo "-- adding new solana key file"
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          solana-keygen new -o $HOME/.config/solana/id.json

          echo "Installing Serum >> "
          npm i -g @project-serum/anchor@0.18.2 
          npm i -g @project-serum/anchor-cli@0.18.2

          echo "Installing others dependencies >>"
          npm i -g typescript
          npm install -g mocha
          npm install -g ts-mocha

      - id: linting-projects
        name: 🔦 Linting Bulldozer Platform projects
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          npx nx affected --target=build --base=origin/master

      - id: testing-projects
        name: 🧪 Testing Bulldozer Platform projects
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          npx nx affected --target=test --base=origin/master

      - id: building-projects
        name: 🏗️ Building Bulldozer Platform projects
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          npx nx affected --target=build --base=origin/master
